---
title: "სამზრუნველოს წევრები"
description: |
site: distill::distill_website
---

ონტოფოში ბიბლიოთეკა 1912 წლის 5 მარტს დაარსდა. მის განვითარებაზე, შენარჩუნებაზე ონტოფოს ბიბლიოთეკის სამზრუნველოს წევრები ბესარიონ, ბართლომე, ბადრი ნადარეიშვილები, ვლადიმერ ჩიხლაძე, გვრიტო ჭანტურაია და სხვები ზრუნავდნენ.

მათი ძალისხმევით შთაგონებულებმა 111 წლის შემდეგ გადავწყვიტეთ შევუერთდეთ ამ ტრადიციას და ჩვენი წვლილი შევიტანოთ ბიბლიოთეკის განვითარებაში.

ონტოფოს ბიბლიოთეკის სამზრუნველოს საორგანიზაციო ჯგუფის წევრები

1) სალომე გოჩოლეიშვილი

2) თეონა ნადარეიშვილი

3) თათია ნადარეიშვილი

4) თემურ გუგუშვილი

ონტოფოს ბიბლიოთეკის სამზრუნველოს იდეის გაგრძელების მიზანია ბიბლიოთეკის განვითარება, მისი როგორც საზოგადოებრივ ცენტრად ჩამოყალიბება. ჩვენ გვჯერა, რომ ბიბლიოთეკას შეუძლია მნიშვნელოვანი როლი შეასრულოს ინფორმაციის წვდომის გაუმჯობესებისა და ზოგადად ახალი შესაძლებლობების შექმნის მიმართულებით.

სამზრუნველოს საორგანიზაციო ჯგუფი ღიაა ახალი წევრების მიღებისთვის. დაინტერესების შემთხვევაში მოგვწერეთ [facebook-ზე](https://www.facebook.com/ontofolibrary).




